Repository Link-MIND/TOASTER-Server, pull requests merged in 2024-01, with the labels that each got.

#13 Feature/#9
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/DeleteToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/IsReadDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/SaveToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/IsReadResponse.java
  linkmind/src/main/java/com/app/toaster/controller/valid/Severity.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValid.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/domain/CategoryManagement.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/exception/model/BadRequestException.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: ⚒️ Feat

#16 feature: 카테고리 검색 구현, userId resolver 해결, querydsl 추가
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/config/JpaQueryFactoryConfig.java
  linkmind/src/main/java/com/app/toaster/config/WebConfig.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/CategoryResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchCategoryResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchMainResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/ToastResult.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
Labels: ⚒️ Feat

#18 [Merge] userId resolver webconfig에 등록 및 검색기능 구현 merge
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/config/JpaQueryFactoryConfig.java
  linkmind/src/main/java/com/app/toaster/config/WebConfig.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/DeleteToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/IsReadDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/SaveToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/CategoryResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchCategoryResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchMainResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/ToastResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/IsReadResponse.java
  linkmind/src/main/java/com/app/toaster/controller/valid/Severity.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValid.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/domain/CategoryManagement.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/exception/model/BadRequestException.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, ⚒️ Feat

#17 [Feature] 카테고리 API 개발
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryPriorityDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryTitleDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/CreateCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/DeleteCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/EditCategoryRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesReponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/GetCategoryResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/ToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/ToastFilter.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: ⚒️ Feat

#20 [#19] feature: s3 service, 썸네일 미리보기, 토스트 저장, 토스트 삭제 구현
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/OgRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/parse/OgResponse.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/.gitkeep
  linkmind/src/main/java/com/app/toaster/external/client/aws/AWSConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/S3Service.java
  linkmind/src/main/java/com/app/toaster/service/parse/ParsingService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, ⚒️ Feat

#26 [Feature] 리마인드 관련 API 개발
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/request/timer/CreateTimerRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/timer/UpdateTimerCommentDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/timer/UpdateTimerDateTimeDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/CompletedTimerDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/GetTimerPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/GetTimerResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/WaitingTimerDto.java
  linkmind/src/main/java/com/app/toaster/domain/BaseTimeEntity.java
  linkmind/src/main/java/com/app/toaster/domain/IntegerListConverter.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/Timer/TimerService.java
Labels: ⚒️ Feat

#28 [#21] feature: 유저에 프로필이미지 설정, mypage, settings 페이지 구현
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/UserController.java
  linkmind/src/main/java/com/app/toaster/controller/request/user/UpdateAllowedPush.java
  linkmind/src/main/java/com/app/toaster/controller/response/auth/SignInResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/user/MyPageResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/user/SettingResponse.java
  linkmind/src/main/java/com/app/toaster/domain/User.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/exception/model/net/CustomJavaNetException.java
  linkmind/src/main/java/com/app/toaster/exception/model/net/UnknownHostException.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/AppleSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoAccount.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoUserProfile.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoUserResponse.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/LoginResult.java
Labels: ⚒️ Feat

#32 [Feature] 메인페이지 조회 API 개발
  linkmind/.gitignore
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/config/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/controller/FCMController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/request/fcm/FCMPushRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/domain/FCMMessage.java
  linkmind/src/main/java/com/app/toaster/domain/RecommendSite.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/domain/Topic.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/RecommedSiteRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/service/main/MainService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: ⚒️ Feat

#30 Refactor/#29
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/UserController.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/CategoryResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchMainResult.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/ToastDto.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔧Refactor

#34 Feature/#31
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/external/client/slack/SlackApi.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: ⚒️ Feat

#37 Feature/#33
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/CreateCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: ⚒️ Feat

#42 [#41] fix : toastListDto추가
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesReponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/MainToastDto.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/main/MainService.java
Labels: 🐞 fix

#47 [Merge] merge to develop
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesReponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/MainToastDto.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/main/MainService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔧Refactor

#51 [Feature/#50] 메인페이지 API 쪼개기
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/RecommendSiteController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/UserController.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/WaitingTimerDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/MainToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/main/MainService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: ⚒️ Feat

#44 Refactor/#43
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/SaveToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/DuplicatedResponse.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/AWSConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/ImagePresignedUrlResponse.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/PresignedUrlVO.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/S3Service.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryQueryService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryUpdateService.java
  linkmind/src/main/java/com/app/toaster/service/parse/ParsingService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔧Refactor

#53 [Feature/#52] 카테고리 관련 리팩토링
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryPriorityDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryTitleDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/CreateCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/DeleteCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/EditCategoryRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/timer/UpdateTimerDateTimeDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesReponse.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔧Refactor

#54 [Merge] merge to develop
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/RecommendSiteController.java
  linkmind/src/main/java/com/app/toaster/controller/TimerController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/UserController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryPriorityDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryTitleDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/CreateCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/DeleteCategoryDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/EditCategoryRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/timer/UpdateTimerDateTimeDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/toast/SaveToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesReponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/DuplicatedResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/WaitingTimerDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/MainToastDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/AWSConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/ImagePresignedUrlResponse.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/PresignedUrlVO.java
  linkmind/src/main/java/com/app/toaster/external/client/aws/S3Service.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryQueryService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryUpdateService.java
  linkmind/src/main/java/com/app/toaster/service/main/MainService.java
  linkmind/src/main/java/com/app/toaster/service/parse/ParsingService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, 🔗Merge

#57 [Feature/#56] Timer createAt, updateAt 초기화 안됨 오류 해결
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#58 [Merge] test 브랜치 develop으로 머지
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
Labels: 🔗Merge

#61 [Merge] merge to develop
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔗Merge

#64 [#63] refactor: 작업을 위한 토큰 시간 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor

#66 Fix/#65
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/AppleSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/response/ApplePublicKeys.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/verify/AppleJwtParser.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/verify/PublicKeyGenerator.java
Labels: 🐞 fix

#69 [#68] refactor: 로그인 리스폰스 fcm 수정
  linkmind/src/main/java/com/app/toaster/controller/response/auth/SignInResponseDto.java
Labels: 🔧Refactor

#70 [Merge] response naming 수정
  linkmind/src/main/java/com/app/toaster/controller/response/auth/SignInResponseDto.java
Labels: 🔗Merge

#72 [#71] fix: 타이머 포맷 한국시간으로 설정
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#73 [Merge] 한국 시간 변경 merge
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, 🔗Merge

#75 [#71] fix: Timezone 설정
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#76 [Merge] test 브랜치 머지
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔗Merge

#77 [#74] refactor: 거의 무한에 가까운 토큰시간으로 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor

#78 [Merge] 토큰 시간 무제한으로 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔗Merge

#80 [Refactor] 클라 요청에 따른 카테고리 전체 조회 수정
  README.md
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoryResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/model/ForbiddenException.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔧Refactor

#81 [Feature] 타이머 시간 계산 & 포맷 로직 수정
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, ⚒️ Feat

#82 [Merge] 클라 요청에 따른 변경사항들 merge
  linkmind/src/main/java/com/app/toaster/ToasterApplication.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoriesResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/category/CategoryResponse.java
  linkmind/src/main/java/com/app/toaster/controller/response/main/MainPageResponseDto.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/model/ForbiddenException.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#84 [#83] refactor: search에서 검색어 클라요청으로 추가
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchMainResult.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
Labels: 🔧Refactor

#85 [Merge] 검색 기능에 response 추가
  linkmind/src/main/java/com/app/toaster/controller/response/search/SearchMainResult.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
Labels: 🔗Merge

#87 [#86] refactor: 토큰 시간 1분 3분으로 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor

#88 [Merge] 토큰시간 변경 merge
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔗Merge

#90 [#89] refactor: 에러코드 수정
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔧Refactor

#91 [Merge] 오류코드 수정 merge
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#93 [#92] refactor: 토큰 시간 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🐞 fix, 🔧Refactor, 🔗Merge

#94 [Refactor] enum type 에러 제거
  linkmind/src/main/java/com/app/toaster/domain/RecommendSite.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🐞 fix, 🔧Refactor

#97 [Fix] 리마인드가 존재하는 카테고리 삭제
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔧Refactor

#98 [Merge] 카테고리 삭제 관련 이슈 임시방편으로 막음.
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔗Merge

#102 [#101] refactor: 토큰시간 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor, 🔗Merge

#106 Refactor/#105
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/response/user/SettingResponse.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🐞 fix, 🔧Refactor

#107 [Merge] 오타 변경 후 merge
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/response/user/SettingResponse.java
Labels: 🐞 fix, 🔗Merge

#110 [#108] fix: 세부 카테고리 로직 수정
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#111 [fix] 리마인드가 존재하지않는 카테고리 삭제
  linkmind/src/main/java/com/app/toaster/domain/Category.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#115 [#114] refactor: filter 로직 수정
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🔧Refactor

#116 [Feature] 카테고리 수정 API 두개로 분리
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, ⚒️ Feat

#117 [Merge] 각종 에러 해결
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔗Merge

#119 [fix] @TitleValid 수정
  README.md
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryTitleDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/EditCategoryRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
Labels: 🐞 fix, ⚒️ Feat

#120 [Merge] @TitleValid 수정
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/ChangeCateoryTitleDto.java
  linkmind/src/main/java/com/app/toaster/controller/request/category/EditCategoryRequestDto.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
Labels: 🔗Merge

#122 [Feature/#121] 400 공통 에러 추가
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/service/parse/ParsingService.java
Labels: ⚒️ Feat

#124 [Fix] 전체카테고리 리마인더 생성가능하게 변경
  linkmind/src/main/java/com/app/toaster/controller/response/timer/CompletedTimerDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/WaitingTimerDto.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, ⚒️ Feat

#126 [fix] 유저별 전체카테고리 중복체크
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#128 [Feature] 푸시알림 구현
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/config/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/controller/FCMController.java
  linkmind/src/main/java/com/app/toaster/controller/request/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/GetTimerResponseDto.java
  linkmind/src/main/java/com/app/toaster/domain/User.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMPushRequestDto.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/ScheduleConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConsumer.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: ⚒️ Feat

#127 [#100] feature: nickname가져오기
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/AppleSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/LoginResult.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/Strategy.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: ⚒️ Feat

#129 [Merge] 회원탈퇴, 푸시알림 붙이기
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/config/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/FCMController.java
  linkmind/src/main/java/com/app/toaster/controller/request/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/controller/response/timer/GetTimerResponseDto.java
  linkmind/src/main/java/com/app/toaster/domain/User.java
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMPushRequestDto.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/ScheduleConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConsumer.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
  linkmind/src/main/java/com/app/toaster/infrastructure/TimerRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/apple/AppleSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/LoginResult.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/Strategy.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, ⚒️ Feat, 🔗Merge

#131 [fix] 에러 코드 변경 및 merge 오류 해결
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, 🔧Refactor

#134 [#133] refactor: 토큰시간 변경
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor, 🔗Merge

#136 [fix] 타이머 생성 및 수정시 푸시알림 완료전 DB로 데이터 flush
  .github/workflows/CD.yml
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#137 [Merge] 타이머 생성및 수정시 푸시알림 오류 해결 develop에 머지
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, 🔗Merge

#140 [#139] refactor: deleteCategory 쿼리파라미터로 변경
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔧Refactor

#141 [Merge] delete category merge
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔗Merge

#144 [Feature] 이주의 추천 링크 엔티티 및 api 수정
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/domain/Link.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/infrastructure/LinkRepository.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, ⚒️ Feat

#143 [#142] refactor: 회원탈퇴 다시 구현
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
Labels: 🔧Refactor

#145 [Merge] Test merge
  linkmind/src/main/java/com/app/toaster/controller/AuthController.java
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/domain/Link.java
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/infrastructure/LinkRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#147 [#138] refactor: Link Dto 네이밍 변경
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekLinkDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔧Refactor

#148 [ Merge] test branch merge
  linkmind/src/main/java/com/app/toaster/controller/ToastController.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekLinkDto.java
  linkmind/src/main/java/com/app/toaster/controller/response/toast/WeekSiteDto.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#150 [Feature] 우선순위 변경 오류 해결
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#153 [Feature] 예약된 스케줄링 모두 제거하는 test api
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: ⚒️ Feat

#155 [Merge] 용감한 미혜
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/controller/CategoryController.java
  linkmind/src/main/java/com/app/toaster/controller/MainController.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValid.java
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
  linkmind/src/main/java/com/app/toaster/domain/Reminder.java
  linkmind/src/main/java/com/app/toaster/exception/Success.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔗Merge

#156 [fix]: 대기중인 시간 오름차순 정렬
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#157 [Merge] 대기중인 타이머 정렬 변경사항 merge
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔗Merge

#158 [Fix] 알람 켜진 여부 정렬 반대조건으로 바꾸기
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#159 [Merge] 정렬 로직 변경 후 merge
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🔗Merge

#161 [fix] 클립 최대 개수 제한 조건 변경
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔧Refactor

#164 Refactor/#163
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🐞 fix, 🔧Refactor

#162 [Merge] 각종 오류 해결 후 merge
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔧Refactor, 🔗Merge

#168 [Fix] 마이페이지 개수 로직 변경
  linkmind/src/main/java/com/app/toaster/domain/Toast.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix

#166 [Fix] 클립 총 개수 세는 로직 변경
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
Labels: 🐞 fix

#171 [Refactor/#170] 카카오톡에서 프로필 사진 안가져오기
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor

#172 [Merge] 카카오톡 프로필 이미지 안쓰기.
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
Labels: 🔧Refactor, 🔗Merge

#174 [#173] refactor: ww.형식으로 토스트 저장요청 시 400
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/domain/User.java
Labels: 🔧Refactor

#175 [Merge] 오류 해결 후 merge
  linkmind/src/main/java/com/app/toaster/common/advice/ControllerExceptionAdvice.java
  linkmind/src/main/java/com/app/toaster/domain/User.java
Labels: 🔗Merge

#178 [Fix] 읽었을때 updateAt 바꾸는 조건 변경
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix

#179 [Merge] 열람 여부 로직 수정
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#180 MERGE
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🔗Merge

#182 [#181] refactor: 카테고리 열람 여부에 따른 전체 개수 수정
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix, 🔧Refactor

#183 [Merge] 버그 fix
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🔗Merge

#187 [Merge] graceful shut down 추가
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/exception/Error.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/GracefulShutdown.java
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, 🔗Merge

#189 [#185] fix: transactionManager 추가
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
Labels: 🐞 fix

#190 [Merge] transactionalTest
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
Labels: 🐞 fix, 🔗Merge

#191 [#188] refactor: readonly등 추가
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, 🔧Refactor

#192 [#184] 카테고리 이름 중복 체크 유저마다로 변경
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#193 [Merge] 각종 버그 해결
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/UserService.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/search/SearchService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
  linkmind/src/main/java/com/app/toaster/service/toast/ToastService.java
Labels: 🐞 fix, 🔧Refactor, 🔗Merge

#194 [fix] 카테고리 중복체크 시 유저 설정
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#195 [Merge] 카테고리 중복 체크시 유저 반영
  linkmind/src/main/java/com/app/toaster/infrastructure/CategoryRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
Labels: 🐞 fix

#197 [fix] sqs groupd Id timerId로 변경
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
Labels: 🐞 fix

#201 [Feature/#200] 카톡 서버 회원탈퇴 구현
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
Labels: ⚒️ Feat

#199 [ Fix] : 이주의 링크 일주일마다 랜덤으로 보여주기
  linkmind/src/main/java/com/app/toaster/domain/Link.java
  linkmind/src/main/java/com/app/toaster/domain/RecommendSite.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
  linkmind/src/main/java/com/app/toaster/infrastructure/LinkRepository.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
Labels: 🐞 fix, ⚒️ Feat

#202 [Merge] test branch merge
  linkmind/src/main/java/com/app/toaster/domain/Link.java
  linkmind/src/main/java/com/app/toaster/domain/RecommendSite.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
  linkmind/src/main/java/com/app/toaster/infrastructure/LinkRepository.java
  linkmind/src/main/java/com/app/toaster/service/auth/AuthService.java
  linkmind/src/main/java/com/app/toaster/service/auth/kakao/KakaoSignInService.java
  linkmind/src/main/java/com/app/toaster/service/link/LinkService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
Labels: 🔗Merge

#205 [Merge] 정규표현식 수정 후 merge
  linkmind/src/main/java/com/app/toaster/controller/valid/TitleValidator.java
Labels: 🐞 fix, 🔗Merge

#207 [Fix] 타이머 요일 정렬해서 저장
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#208 [Merge] 요일 정렬 merge
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix, 🔗Merge

#211 [Fix] 완료된 타이머 계산 로직 변경
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#214 [Fix] 토스터 정렬 최근 추가순으로 정렬
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
Labels: 🐞 fix

#215 [Merge] 요일 정렬
  linkmind/src/main/java/com/app/toaster/infrastructure/ToastRepository.java
  linkmind/src/main/java/com/app/toaster/service/category/CategoryService.java
  linkmind/src/main/java/com/app/toaster/service/recommendSite/RecommendSiteService.java
Labels: 🔗Merge

#217 [Fix] 타이머 스케줄 부하 해결
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix

#218 Merge
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
Labels: 🔗Merge

#220 [Feature/#219] 타이머 알람 로직 삭제
  linkmind/build.gradle
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMController.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMPushRequestDto.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMScheduler.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/FCMService.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/GracefulShutdown.java
  linkmind/src/main/java/com/app/toaster/external/client/fcm/PushMessage.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/ScheduleConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConfig.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsConsumer.java
  linkmind/src/main/java/com/app/toaster/external/client/sqs/SqsProducer.java
  linkmind/src/main/java/com/app/toaster/service/timer/TimerService.java
Labels: 🐞 fix
